# Copied from azure-rest-api-specs/.github/workflows/_reusable-eng-tools-test.yaml

name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows]
        node-version: [22, 24]
        exclude:
          - os: ubuntu
            node-version: 24
          - os: windows
            node-version: 22

    runs-on: ${{ fromJSON('{"ubuntu":"ubuntu-24.04", "windows":"windows-2022"}')[matrix.os] }}

    steps:
      - if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - uses: actions/checkout@v6

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          echo "::group::npm ci"
          npm ci
          echo "::endgroup::"
          echo "::group::npm ls -a"
          npm ls -a || true
          echo "::endgroup::"
        shell: bash

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Lint
        run: npm run lint

      - name: Check Formatting
        run: npm run format:check:ci

      - if: runner.os == 'Linux'
        name: Pack
        run: npm pack

      - if: runner.os == 'Linux'
        name: Upload tarball
        uses: actions/upload-artifact@v7
        with:
          path: 'azure-avocado-*.tgz'
          archive: false

      # Content copied from https://raw.githubusercontent.com/rhysd/actionlint/2ab3a12c7848f6c15faca9a92612ef4261d0e370/.github/actionlint-matcher.json
      - if: runner.os == 'Linux'
        name: Add ActionLint Problem Matcher
        run: echo "::add-matcher::.github/matchers/actionlint.json"

      - if: runner.os == 'Linux'
        name: Lint workflows
        uses: docker://rhysd/actionlint:1.7.11
        with:
          args: -color -verbose
